version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - yum update -y
      - yum install -y nginx
      - yum install -y wget  
      - yum install git -y
      - yum install -y python3-pip gcc python3-devel
      - yum install mariadb-server mariadb-client -y
      - yum groupinstall "Development Tools" -y
      - yum install bzip2-devel libffi-devel -y

  pre_build:
    commands:
      - export HOME=/root
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - cd /
      - git clone "https://git-codecommit.us-east-2.amazonaws.com/v1/repos/$REPOSITORY_NAME"

  build:
    commands:
      - cd /hellowaws-application-sourcecode/django-community-board-main/
      - pip install --no-cache-dir -r ./requirements.txt

  post_build:
    commands:
      - echo "Build 단계 완료"

artifacts:
  files:
    - '**/*'
  name: "build_output/1.zip"