version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - yum update -y
      - yum install -y wget  
      - yum install git -y
      - yum install pkgconfig -y
      - yum install -y python3-pip 
      - yum install -y gcc 
      - yum install -y python3-devel
      - yum groupinstall "Development Tools" -y
      - yum install bzip2-devel libffi-devel -y

  pre_build:
    commands:
      - export HOME=/root
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - cd /
      - git clone "https://git-codecommit.$AWS_DEFAULT_REGION.amazonaws.com/v1/repos/$REPOSITORY_NAME"

  build:
    commands:
      - cd /hellowaws-application-sourcecode/django-community-board-main/
      - db_user_id=$(aws ssm get-parameter --name "/config/account/admin/ID" --with-decryption --query "Parameter.Value" --output text --region $AWS_DEFAULT_REGION)
      - db_user_pwd=$(aws ssm get-parameter --name "/config/account/admin/PWD" --with-decryption --query "Parameter.Value" --output text --region $AWS_DEFAULT_REGION)
      - aurora_endpoint=$(aws ssm get-parameter --name "/config/system/db-cluster-endpoint" --with-decryption --query "Parameter.Value" --output text --region $AWS_DEFAULT_REGION)
      - redis_endpoint=$(aws ssm get-parameter --name "/config/system/redis-cluster-endpoint" --with-decryption --query "Parameter.Value" --output text --region $AWS_DEFAULT_REGION)
      - export db_user_id
      - export db_user_pwd
      - export aurora_endpoint
      - export redis_endpoint
      - envsubst < ./templates/settings.py.template > ./community_board_project/settings.py

  post_build:
    commands:
      - echo "Build 단계 완료"
      - cd /hellowaws-application-sourcecode/
      - zip -r build_output.zip .

artifacts:
  files:
    - '**/*'
  name: "build_output.zip"